### ISSUE TITLE
Origins of source code

### ISSUE THREAD

**Issue by acagastya** [o-nly/klisp#1]
Hi, @o-nly.  I tried accessing klisp's source code on its website, which refers to bitbucket.org.  However, it looks like the code is no longer available.  ([See archived link](http://web.archive.org/web/20190905192640if_/https://bitbucket.org/AndresNavarro/klisp/src/default/)).  I wondered if this was the original source code that @AndresNavarro82 had put up on BitBucket.  Did Andres Navarro also maintain a repo on GitHub which you had forked?

**Comment by AndresNavarro82** [comment]
Hi, Andres Navarro here. 
It's been years since I worked on this, but lately I've been intending to upload it again at least to keep a copy online.
The original repo is in mercurial (so I should have a local copy on my old pc), and it was hosted in bitbucket.  For some reason at one point bitbucket deleted all the repos, and I didn't even notice...  I think I had a github mirror, maintained via a mercurial->git converter, but it had some issues and I deleted it at some point.  In any case, I'll try to look for it this week, upload the last version to github (with the revision history if possible) and update the webpage.

Feel free to contact me at canavarro82@gmail.com

Regards, 
Andres Navarro

**Comment by acagastya** [comment]
Ah, thanks for the prompt response, @AndresNavarro82.  If we can get the commit history, that would be greatly appreciated.  It is rather unfortunate there aren't official repos available on the internet -- I will mirror it as soon as you put it online.  :D
